---
- name: "[CentOS_7_x86_64] install needed packages"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - device-mapper-persistent-data
    - lvm2
    - awk 

- name: "[CentOS_7_x86_64] Remove docker-ce.repo"
  file:
    path: /etc/yum.repos.d/docker-ce.repo
    state: absent

- name: "[CentOS_7_x86_64] Add Docker CE repository"
  get_url:
    url: "{{ centos_7_x86_64_repo_url }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644

- name: "[CentOS_7_x86_64] Install Docker CE"
  yum:
    name: docker-ce
    state: present
  when: swarm_upgrade == false

- name: "[CentOS_7_x86_64] Upgrade Docker CE"
  yum:
    name: docker-ce
    state: latest
  when: swarm_upgrade == true
  notify:
    - restart_docker-ce

- name: "[CentOS_7_x86_64] Docker CE systemd enabled/autostart"
  service:
    name: docker
    state: started
    enabled: yes

# Managers tasks
- name: "[CentOS_7_x86_64] [Managers]"
  include: managers.yml
  when: "'managers' in group_names"

# Workers tasks
- name: "[CentOS_7_x86_64] [Workers]"
  include: workers.yml
  when: "'workers' in group_names"